# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  
  # Base box being used
  config.vm.box = "modernIE/w7-ie11"
  
  # Windows box uses winrm
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  
  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
  
	 # Starts the GUI
     vb.gui = true
	 
	 # Allocate 2GB RAM
     vb.memory = "2048"
	 
	 # Set the box name
	 vb.name = "Currituck-pmchen-TraceLab"
	 
   end
   
  # Get files on desktop
  config.vm.provision "shell", path: "get-files.bat"
  
  # Get and install TraceLab
  config.vm.provision "shell", path: "inst-tool.bat"
  
end
