Vagrant.configure(2) do |config|
  config.vm.box = "modernIE/w7-ie11"
  #config.vm.boot_timeout = 300
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end
   
  #config.ssh.username = "IEUser"
  #config.ssh.password = "Passw0rd!"
  config.vm.provision "shell", path: "bootstrap.bat"
  
end
